// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for converting manually written test cases into Gherkin format.
 *
 * - convertManualToGherkin - A function that takes manual test case text and generates Gherkin.
 * - ConvertManualToGherkinInput - The input type for the convertManualToGherkin function.
 * - ConvertManualToGherkinOutput - The return type for the convertManualToGherkin function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ConvertManualToGherkinInputSchema = z.object({
  manualTestCases: z.string().describe('The manually written test cases or descriptions.'),
  featureName: z.string().describe('An optional desired name for the Gherkin Feature.').optional(),
});
export type ConvertManualToGherkinInput = z.infer<typeof ConvertManualToGherkinInputSchema>;

const ConvertManualToGherkinOutputSchema = z.object({
  generatedGherkin: z.string().describe('The generated Gherkin feature file content.'),
});
export type ConvertManualToGherkinOutput = z.infer<typeof ConvertManualToGherkinOutputSchema>;

export async function convertManualToGherkin(input: ConvertManualToGherkinInput): Promise<ConvertManualToGherkinOutput> {
  return convertManualToGherkinFlow(input);
}

const prompt = ai.definePrompt({
  name: 'convertManualToGherkinPrompt',
  input: {schema: ConvertManualToGherkinInputSchema},
  output: {schema: ConvertManualToGherkinOutputSchema},
  prompt: `You are an expert in Behavior-Driven Development (BDD) and Gherkin syntax.
Your task is to convert the following manually written test cases into a well-structured Gherkin feature file.

Instructions:
1.  If a "Desired Feature Name" is provided, use that for the "Feature:" line. If not, try to infer an appropriate and descriptive feature name from the context of the manual test cases.
2.  Organize the test cases into clear "Scenario:" blocks. If the manual tests imply parameterized examples, use "Scenario Outline:" with an "Examples:" table.
3.  Transform the manual test steps into Gherkin steps using appropriate keywords: "Given", "When", "Then", "And", "But".
4.  Ensure the Gherkin syntax is correct and the output is clean and readable.
5.  Capture the essence of each manual test case in the generated Gherkin scenario.
6.  Only output the Gherkin text. Do not include any other explanations or introductory text.

Manual Test Cases:
\`\`\`
{{{manualTestCases}}}
\`\`\`

{{#if featureName}}
Desired Feature Name: {{{featureName}}}
{{/if}}

Generated Gherkin:
\`\`\`gherkin
// Generated Gherkin will appear here
\`\`\`
Ensure the generated Gherkin is placed within the final code block marker above.
`,
});

const convertManualToGherkinFlow = ai.defineFlow(
  {
    name: 'convertManualToGherkinFlow',
    inputSchema: ConvertManualToGherkinInputSchema,
    outputSchema: ConvertManualToGherkinOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
