// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow to suggest Gherkin test cases based on a feature description.
 *
 * - suggestGherkinTestCases - A function that suggests Gherkin test cases based on a feature description.
 * - SuggestGherkinTestCasesInput - The input type for the suggestGherkinTestCases function.
 * - SuggestGherkinTestCasesOutput - The return type for the suggestGherkinTestCases function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestGherkinTestCasesInputSchema = z.object({
  featureDescription: z.string().describe('A description of the feature to generate Gherkin test cases for.'),
});
export type SuggestGherkinTestCasesInput = z.infer<typeof SuggestGherkinTestCasesInputSchema>;

const SuggestGherkinTestCasesOutputSchema = z.object({
  suggestedTestCases: z.string().describe('The suggested Gherkin test cases.'),
});
export type SuggestGherkinTestCasesOutput = z.infer<typeof SuggestGherkinTestCasesOutputSchema>;

export async function suggestGherkinTestCases(input: SuggestGherkinTestCasesInput): Promise<SuggestGherkinTestCasesOutput> {
  return suggestGherkinTestCasesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestGherkinTestCasesPrompt',
  input: {schema: SuggestGherkinTestCasesInputSchema},
  output: {schema: SuggestGherkinTestCasesOutputSchema},
  prompt: `You are a test automation engineer. Suggest Gherkin test cases for the following feature description:\n\n{{featureDescription}}`,
});

const suggestGherkinTestCasesFlow = ai.defineFlow(
  {
    name: 'suggestGherkinTestCasesFlow',
    inputSchema: SuggestGherkinTestCasesInputSchema,
    outputSchema: SuggestGherkinTestCasesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
